#!/usr/bin/env bash
#Prints ertian strings depending on file status
if [ -e "holbertonschool" ]
then
	echo "school file exists"

	if [ -s "school" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [ -f "school" ]
	then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi
